# Generated by Django 4.2.7 on 2023-11-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(blank=True, error_messages={'unique': 'Este domínio já está cadastrado.'}, max_length=100, null=True, unique=True, verbose_name='Domínio')),
                ('url_ssls', models.CharField(blank=True, max_length=100, null=True, verbose_name='URL ssls')),
                ('ativacao_ssl', models.DateField(blank=True, null=True, verbose_name='Data início certificado')),
                ('validade_ssl', models.DateField(blank=True, null=True, verbose_name='Data fim certificado')),
                ('emissor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emissor')),
                ('status_ssl', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Vencido', 'Vencido'), ('Abandonado', 'Abandonado'), ('Último dia', 'Último dia'), ('Disponível', 'Disponível'), ('Inconsistente', 'Inconsistente')], max_length=13, verbose_name='Status SSL')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data cadastro')),
            ],
        ),
    ]
