# Generated by Django 4.2.6 on 2023-10-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id_ssl', models.AutoField(primary_key=True, serialize=False)),
                ('dominio', models.TextField(max_length=255)),
            ],
        ),
    ]
