# Generated by Django 4.2.6 on 2023-10-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='validade',
            field=models.DateField(null=True),
        ),
    ]
