# Generated by Django 4.2.6 on 2023-10-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificados',
            new_name='Certificado',
        ),
    ]
