# Generated by Django 4.2.6 on 2023-11-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0002_alter_certificado_validade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificado',
            new_name='Cert',
        ),
    ]
