# Generated by Django 4.2.6 on 2023-10-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0002_rename_certificados_certificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='id_ssl',
            new_name='id_certificado',
        ),
    ]
