# Generated by Django 4.2.6 on 2023-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0003_rename_certificado_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='dominio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cert',
            name='url_ssls',
            field=models.CharField(max_length=100),
        ),
    ]
