# Generated by Django 4.2.6 on 2023-10-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0003_rename_id_ssl_certificado_id_certificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='id_certificado',
            new_name='id_ssl',
        ),
    ]
