# Generated by Django 4.2.7 on 2023-11-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0004_alter_cert_status_ssl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='status_ssl',
            field=models.CharField(choices=[('None', '-'), ('A', 'Ativo'), ('I', 'Inativo'), ('V', 'Vencido'), ('O', 'Abandonado')], default=None, max_length=4, verbose_name='Status SSL'),
        ),
    ]
