# Generated by Django 4.2.6 on 2023-11-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0004_alter_cert_dominio_alter_cert_url_ssls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data cadastro'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='dominio',
            field=models.CharField(max_length=100, verbose_name='Domínio'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='url_ssls',
            field=models.CharField(max_length=100, null=True, verbose_name='URL ssls'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='validade',
            field=models.DateField(null=True, verbose_name='Validade certificado'),
        ),
    ]
