# Generated by Django 4.2.7 on 2023-11-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0005_alter_cert_status_ssl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='status_ssl',
            field=models.CharField(choices=[('None', '-'), ('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Vencido', 'Vencido'), ('Abandonado', 'Abandonado')], default=None, max_length=10, verbose_name='Status SSL'),
        ),
    ]
