# Generated by Django 4.2.7 on 2023-11-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ssl', '0006_alter_cert_status_ssl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cert',
            old_name='organizacao',
            new_name='issuer',
        ),
    ]
