version: "3.7"

services:
  mongo-db:
    image: mongo:4.4.26
    restart: unless-stopped
    container_name: mongo-db
    volumes:
      - mongo-data:/data
    networks:
      - app-network
    # ports:
    #   - "27017:27017"

  django-backend:
    build: django
    image: django-backend
    restart: unless-stopped
    container_name: django-backend
    networks:
      - app-network
    depends_on:
      - mongo-db
    # volumes:
    #   - ./django:/app/django
    ports:
      - "8000:8000"

  nuxt-frontend:
    build: front
    image: nuxt-frontend
    restart: unless-stopped
    container_name: nuxt-frontend
    networks:
      - app-network
    depends_on:
      - django-backend
    # volumes:
    #   - ./front/.output/public/:/var/www
    ports:
      - "80:80"

volumes:
  mongo-data:

networks:
  app-network: