version: "3.7"

services:
  mariadb:
    image: mariadb:11.4.1
    restart: unless-stopped
    container_name: mariadb
    volumes:
      - /data/mariadb:/var/lib/mysql/
    networks:
      - app-network
    ports:
      - "3306:3306"

  ssl-django:
    image: ${gitlab_registry}/ssl-django:latest
    restart: unless-stopped
    container_name: ssl-django
    networks:
      - app-network
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    environment:
      SERVER_IP: ${SERVER_IP}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

  ssl-nuxt:
    image: ${gitlab_registry}/ssl-nuxt:latest
    restart: unless-stopped
    container_name: ssl-nuxt
    networks:
      - app-network
    depends_on:
      - ssl-django
    ports:
      - "443:443"
    environment:
      VITE_API_URL: ${VITE_API_URL}

networks:
  app-network: