# Generated by Django 4.2.7 on 2023-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domain')),
                ('ssls_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='SSL URL')),
                ('activation_ssl', models.DateField(blank=True, null=True, verbose_name='Certificate start date')),
                ('expiration_ssl', models.DateField(blank=True, null=True, verbose_name='Certificate end date')),
                ('activation_weekday', models.CharField(blank=True, max_length=100, null=True, verbose_name='Activation day')),
                ('expiration_weekday', models.CharField(blank=True, max_length=100, null=True, verbose_name='Expiration day')),
                ('issuer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Issuer')),
                ('status_ssl', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired'), ('Abandoned', 'Abandoned'), ('Last day', 'Last day'), ('Available', 'Available'), ('Inconsistent', 'Inconsistent')], max_length=13, verbose_name='SSL Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
            ],
        ),
    ]
